### ISSUE TITLE
Is it possible to connect to a remote server from a local client

### ISSUE THREAD

**Issue by georgebutter** [floatinghotpot/socket.io-unity#16]
I don't want to host the game in the same place the server is hosted. 

Can sockets be connected to from a different origin?

I have read that they have a same origin policy but is there a work around for this?

**Comment by dpaikin** [comment]
They can be connected from a different origin seamlessly I believe.

**Comment by georgebutter** [comment]
Yes I managed to get this working, thank you :+1:
