### ISSUE TITLE
Unity Package Manager UI Error after updating from 2017.3 to 2018.1.0f2

### ISSUE THREAD

**Issue by ghost** [floatinghotpot/socket.io-unity#31]
After Upgrade to Unity v2018 i got a Unity Package Manager UI Error. I found some guy who has the same issue:

https://answers.unity.com/questions/1505376/unity-package-manager-ui-error-after-updating-from.html

![116758-unity-error](https://user-images.githubusercontent.com/3317869/40391810-d2a63ac2-5e19-11e8-8994-471ddb546727.png)

Workaround: Downgrade to Unity v2017

**Comment by Zbluu** [comment]
Same issue for me, after upgrade to Unity 2018.
You can use this solution in the meantime : "A workaround is to delete the unity package manager ui folder from your cache at C:\Users{Your Username Here}\AppData\Local\Unity\cache\packages\packages.unity.com"

**Comment by cikocaus** [comment]
I tried to delete the cache folder but this don't work for me. It's a small project so i can complete this Project with Unity2017.  I only want to notify @floatinghotpot and other devs which use this Framework.
